### ISSUE TITLE
Limit this to Instagram only

### ISSUE THREAD

**Issue by aashutoshrathi** [aashutoshrathi/Insta-Downloader-Extension#1]
Currently, not bounded by any URL pattern, works on all. We need it to be only operated on https://www.instagram.com/

**Comment by prattheev** [comment]
@aashutoshrathi That's easy. Watch out for my PR!

**Comment by aashutoshrathi** [comment]
Okay 👍

**Comment by aashutoshrathi** [comment]
Actually @prattheev I just realised that I already took care of it here: https://github.com/aashutoshrathi/Insta-Downloader-Extension/blob/6e9c32e58f55e20216819f646b1cddb137dd7cd7/manifest.json#L26
