### ISSUE TITLE
Displaying three buttons for same profile pic

### ISSUE THREAD

**Issue by lalitmee** [aashutoshrathi/Insta-Downloader-Extension#37]
There are some bugs which I noticed such as
1. Three buttons are showing for downloading the same profile pic after scrolling.
2. `Download Dp` button is only showing for the first pic on the page.
3. Alignment issue in the button for downloading the current user's profile pic. That should be aligned with the image.

I would like to take some time and work on these issues. :+1: :smiley: 

Here is a screenshot of what I noticed
![selection_021](https://user-images.githubusercontent.com/10762218/50305720-b72ab100-04b9-11e9-96de-7eab55c2d26d.png)

**Comment by aashutoshrathi** [comment]
Yes, I'm fixing that actually main page's map is changed by Instagram recently.

**Comment by aashutoshrathi** [comment]
Moving it to #32 
You can check update there @lalitmee
